package soccer.game.events;

public enum EventTypes {

    // Match start
    PREPARATION_FOR_MATCH_START,
    PREPARATION_FOR_MATCH_START_ALL_PLAYERS_READY,
    MATCH_START,

    // After goal
    GOAL,
    GOAL_ANIMATION_ALL_PLAYERS_READY,
    RESUME_GAME_FROM_THE_MIDDLE,

    // Resume by GK
    RESUME_BY_GK,
    RESUME_BY_GK_ALL_PLAYERS_READY,
    RESUME_BY_GK_PERFORMED,

    // Corner
    CORNER,
    CORNER_ALL_PLAYERS_READY,
    CORNER_PERFORMED,

    // OUT
    OUT,
    OUT_ALL_PLAYERS_READY,
    OUT_PERFORMED,

    // FOUL
    FOUL,

    // Free Kick
    FREE_KICK,
    FREE_KICK_ALL_PLAYERS_READY,
    FREE_KICK_PERFORMED,

    // PENALTY
    PENALTY,
    PENALTY_ALL_PLAYERS_READY,
    PENALTY_PERFORMED,

    // Match Events
    GOAL_POST_HITTED,
    FIRST_PASS_FROM_THE_MIDDLE_PERFORMED,

    // Time
    END_FIRST_HALF,
    MATCH_CREATED, MATCH_INITIALIZED, END_SECOND_HALF


}
